### ISSUE TITLE
XDS neggia assertion failed HD5 superblock line38

### ISSUE THREAD

**Issue by beeokee** [dectris/neggia#23]
This is neggia 1.0.1 (Copyright Dectris 2017)
 [generic_data_plugin] - INFO - generic_get_header
Assertion failed: (version == 0), function H5Superblock, file /mnt/nightly-builds1/gphl/Releases.0/autoPROC1.0/src/hdf5/buildhost6/neggia-master/src/dectris/neggia/data/H5Superblock.cpp, line 38.
xds
^C

**Comment by dirkboye** [comment]
Please upgrade to our newest version of neggia: 1.2.0
see https://github.com/dectris/neggia/releases/tag/v1.2.0

There's also a description on howto check your hdf5 files against compatibility with neggia in the readme.
