### ISSUE TITLE
XDS Neggia assertion failed HD5 superblock line 38

### ISSUE THREAD

**Issue by beeokee** [dectris/neggia#24]
This is neggia 1.0.1 (Copyright Dectris 2017)
 [generic_data_plugin] - INFO - generic_get_header
Assertion failed: (version == 0), function H5Superblock, file /mnt/nightly-builds1/gphl/Releases.0/autoPROC1.0/src/hdf5/buildhost6/neggia-master/src/dectris/neggia/data/H5Superblock.cpp, line 38

**Comment by dirkboye** [comment]
#23 duplicate
