### ISSUE TITLE
Reconsider project name?

### ISSUE THREAD

**Issue by Anthchirp** [dectris/neggia#6]
Even though I know where the project name comes from it appears to me to be dangerously easy to misread.

I am sure there must be alternative mountain passes available in Switzerland that do not suffer from this issue.

**Comment by pnbat** [comment]
I think I already raised that in the past. +1 for a renaming.

**Comment by admindectris** [comment]
Hi, thanks for bringing this up. We have discussed this internally and decided to stick with the current name. As you know, it is indeed a name of a mountain pass in the Italian-speaking part of Switzerland, and the word itself is completely innocent; it's also pronounced something like "neh-jah".

There is indeed a (hopefully very remote!) possibility that someone not familiar with the Swiss landscape or the Italian language will at first glance see something untoward. However, we hope that such an event will be a nice opportunity for people to get to know our beautiful mountain passes and the Italian language better! After all, there are a lot of languages in the world, and a lot of words in those languages will look silly or wrong in other languages. I should know; my native Finnish gets people laughing all the time - some very common phrases we use are obscene curses in Italian, for example...

So we're hoping this can in fact be a step towards diversity and not away from it!

Angina Herrmann, Head of Marketing & Communications, DECTRIS
